---
abstract: "Perl extension for mocking calls to LWP::UserAgent's"
author:
  - 'Jason Clifford <jason@ukfsn.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mock-LWP-Request
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Response: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  Moo: 0
  Test::Exception: 0
version: 0.01
